"use client";
import {useCallback,useEffect,useState} from "react";

type Batch={id:number;provider:string;model_version:string;prompt_version:string;requested_limit:number;created_count:number;existing_count:number;status:string;stop_reason:string|null;completed:number;failed:number;active:number;created_at:string};
type Operations={workers:{worker_id:string;status:string;last_seen_at:string;current_job_id:number|null}[];observations:{metric:string;value_numeric:number|null;value_boolean:boolean|null;observed_at:string}[];safety:{open:boolean;reason_codes:string[];recent_sample:number;failure_rate:number|null;latency_p95_ms:number|null;baseline_sample:number;baseline_failure_rate:number|null;rejected_rate:number|null}};
const STATUS:Record<string,string>={queued:"대기",running:"실행 중",completed:"완료",paused:"중단",cancelled:"취소"};
const REASON:Record<string,string>={provider_failure_rate:"최근 Provider 실패율 초과",provider_latency_p95:"최근 p95 지연 초과",endpoint_unhealthy:"Endpoint 비정상",disk_free_low:"디스크 여유 부족",gpu_memory_low:"GPU 메모리 부족",insufficient_baseline:"확대 실행 표본 부족"};
const metric=(name:string,value:number|null)=>name==="disk_free_bytes"||name==="gpu_memory_free_bytes"?value===null?"-":`${(value/1024**3).toFixed(1)} GiB`:value===null?"-":value.toLocaleString("ko-KR");

export function BatchSafetyDashboard(){const [batches,setBatches]=useState<Batch[]>([]),[ops,setOps]=useState<Operations|null>(null),[error,setError]=useState(false);
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([fetch("/api/translation/batches?limit=20",{cache:"no-store"}),fetch("/api/translation/operations",{cache:"no-store"})]);if(!a.ok||!b.ok)throw new Error();setBatches(((await a.json()) as {batches:Batch[]}).batches);setOps(await b.json() as Operations);setError(false);}catch{setError(true);}},[]);
 useEffect(()=>{const start=setTimeout(()=>void load(),0),timer=setInterval(()=>void load(),15000);return()=>{clearTimeout(start);clearInterval(timer);};},[load]);
 return <section className="batch-safety"><div className="section-heading"><div><p className="eyebrow">BATCH SAFETY</p><h2>배치 안전장치</h2></div><button onClick={()=>void load()}>새로고침</button></div>
 {error?<aside className="snapshot-note snapshot-note--unavailable"><strong>운영 지표 연결 안 됨</strong><span>신규 대량 작업을 시작하지 말고 BE 상태를 확인하세요.</span></aside>:ops?<>
 <div className={`circuit-state ${ops.safety.open?"circuit-state--open":"circuit-state--closed"}`}><div><span>CIRCUIT BREAKER</span><strong>{ops.safety.open?"실행 차단":"실행 가능"}</strong></div><p>{ops.safety.open?ops.safety.reason_codes.map(code=>REASON[code]??code).join(" · "):"최근 오류율·지연·인프라 기준을 통과했습니다."}</p><dl><div><dt>최근 표본</dt><dd>{ops.safety.recent_sample}</dd></div><div><dt>실패율</dt><dd>{ops.safety.failure_rate===null?"-":`${(ops.safety.failure_rate*100).toFixed(1)}%`}</dd></div><div><dt>p95 지연</dt><dd>{ops.safety.latency_p95_ms===null?"-":`${(ops.safety.latency_p95_ms/1000).toFixed(1)}초`}</dd></div><div><dt>확대 표본</dt><dd>{ops.safety.baseline_sample}</dd></div></dl></div>
 <div className="operations-grid"><article><div className="quality-panel-heading"><div><p className="eyebrow">WORKERS</p><h3>Worker heartbeat</h3></div></div>{ops.workers.length?ops.workers.map(row=><div className="operation-row" key={row.worker_id}><strong>{row.worker_id}</strong><span>{row.status} · {new Date(row.last_seen_at).toLocaleString("ko-KR")}</span></div>):<p className="field-empty">아직 heartbeat가 없습니다.</p>}</article><article><div className="quality-panel-heading"><div><p className="eyebrow">INFRASTRUCTURE</p><h3>최근 시스템 표본</h3></div></div>{ops.observations.length?ops.observations.map(row=><div className="operation-row" key={row.metric}><strong>{row.metric}</strong><span>{row.value_boolean===null?metric(row.metric,row.value_numeric):row.value_boolean?"정상":"비정상"}</span></div>):<p className="field-empty">아직 시스템 표본이 없습니다.</p>}</article></div></>:null}
 <div className="quality-risk"><div className="quality-panel-heading"><div><p className="eyebrow">RECENT BATCHES</p><h3>최근 배치</h3></div></div>{batches.length?<div className="table-shell"><table><thead><tr><th>ID</th><th>Provider·모델</th><th>요청·등록</th><th>진행</th><th>상태</th><th>시작</th></tr></thead><tbody>{batches.map(row=><tr key={row.id}><td>{row.id}</td><td>{row.provider} · <code>{row.model_version}</code></td><td>{row.requested_limit} · {row.created_count}</td><td>{row.completed} 완료 · {row.failed} 실패 · {row.active} 활성</td><td><span className={`translation-state translation-state--${row.status}`}>{STATUS[row.status]??row.status}</span></td><td>{new Date(row.created_at).toLocaleString("ko-KR")}</td></tr>)}</tbody></table></div>:<p className="document-empty">등록된 배치가 없습니다.</p>}</div>
 </section>}
