# -*- coding: utf-8 -*-
"""Crawler for Stats NZ Indicators Aotearoa New Zealand records.

The public Stats NZ ``/indicators/`` page now points users to the Shiny app
hosting Nga Tutohu Aotearoa - Indicators Aotearoa New Zealand. The real list
endpoint is generated by that app as a Shiny download endpoint:

    session/<session-id>/download/downloadData?w=<worker-id>

The CSV returned by that endpoint contains one row per time-series observation.
This crawler groups those rows into indicator records, then asks the same Shiny
session to render each indicator route so the saved abstract includes the
public indicator description and metadata.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import re
import subprocess
import time
from collections import OrderedDict
from datetime import datetime
from typing import Dict, List, Optional
from urllib.parse import urlencode

from bs4 import BeautifulSoup

from crawler.base_crawler import BaseCrawler


class _StatsNzShinyClient:
    """Small wrapper around one live Shiny browser session."""

    def __init__(self, crawler: "StatsGovtNzIndicatorsCrawler"):
        self.crawler = crawler
        self._playwright = None
        self._browser = None
        self._page = None

    def start(self):
        try:
            from playwright.sync_api import sync_playwright
        except Exception as exc:
            raise RuntimeError(f"Playwright is required for the Shiny app: {exc}") from exc

        self._playwright = sync_playwright().start()
        self._browser = self._playwright.chromium.launch(headless=True)
        self._page = self._browser.new_page(
            viewport={"width": 1280, "height": 900},
            accept_downloads=False,
        )
        self._page.goto(
            self.crawler.SHINY_APP_URL,
            wait_until="domcontentloaded",
            timeout=self.crawler.BROWSER_TIMEOUT_MS,
        )
        self._page.wait_for_selector(
            ".download-button",
            timeout=self.crawler.BROWSER_TIMEOUT_MS,
        )
        return self

    def close(self):
        for obj in (self._browser, self._playwright):
            if obj is None:
                continue
            try:
                obj.close() if obj is self._browser else obj.stop()
            except Exception:
                pass
        self._page = None
        self._browser = None
        self._playwright = None

    def fetch_all_data_csv(self) -> tuple[str, str]:
        """Return the all-indicators CSV text and its generated endpoint URL."""
        if self._page is None:
            raise RuntimeError("Shiny client has not been started")

        if self._page.locator("#downloadData.shiny-download-link").count() == 0:
            self._page.locator(".download-button").first.click(force=True)
        self._page.wait_for_selector(
            "#downloadData.shiny-download-link",
            timeout=self.crawler.BROWSER_TIMEOUT_MS,
        )
        self._page.wait_for_function(
            """
            () => {
                const link = document.querySelector("#downloadData.shiny-download-link");
                return link && link.href && link.href.includes("/session/");
            }
            """,
            timeout=self.crawler.BROWSER_TIMEOUT_MS,
        )

        endpoint = self._page.locator("#downloadData").evaluate("el => el.href")
        last_error = ""
        for _ in range(6):
            text = self._page.evaluate(
                """
                async (href) => {
                    const response = await fetch(href, {credentials: "include"});
                    const body = await response.text();
                    return {
                        ok: response.ok,
                        status: response.status,
                        body: body
                    };
                }
                """,
                endpoint,
            )
            body = (text.get("body") or "").lstrip("\ufeff")
            first_line = body.splitlines()[0] if body.splitlines() else ""
            if text.get("ok") and "indicator_name" in first_line:
                try:
                    self._page.evaluate(
                        """
                        () => {
                            const wrapper = document.querySelector("#shiny-modal-wrapper");
                            if (wrapper) wrapper.remove();
                            document.body.classList.remove("modal-open");
                            document.querySelectorAll(".modal-backdrop").forEach(el => el.remove());
                        }
                        """
                    )
                except Exception:
                    pass
                return body, endpoint
            last_error = f"HTTP {text.get('status')} first line {first_line[:120]!r}"
            self._page.wait_for_timeout(1000)
        raise RuntimeError(f"downloadData endpoint did not return indicator CSV: {last_error}")

    def fetch_indicator_detail(self, record: Dict[str, object]) -> Dict[str, str]:
        """Render an indicator route and return the relevant HTML snippets."""
        if self._page is None:
            raise RuntimeError("Shiny client has not been started")

        title = str(record.get("indicator_name") or "")
        if not title:
            raise RuntimeError("record has no indicator_name")

        path = self.crawler._route_path(record)
        self._page.evaluate(
            """
            (path) => {
                history.pushState(path, null, path);
                Shiny.setInputValue("clientdata_url_state", path, {priority: "event"});
                Shiny.onInputChange("route_state_changed", path);
            }
            """,
            path,
        )
        self._page.wait_for_function(
            """
            (title) => {
                const heading = document.querySelector("#main_panel-indicator_description h1");
                return heading && heading.innerText.trim() === title;
            }
            """,
            arg=title,
            timeout=self.crawler.BROWSER_TIMEOUT_MS,
        )
        return self._page.evaluate(
            """
            () => {
                const html = (selector) => {
                    const node = document.querySelector(selector);
                    return node ? node.innerHTML : "";
                };
                const text = (selector) => {
                    const node = document.querySelector(selector);
                    return node ? node.innerText : "";
                };
                const source = document.querySelector("#main_panel-update_source_html a#url-link");
                return {
                    "description_html": html("#main_panel-indicator_description"),
                    "summary_html": html("#main_panel-indicator_summary"),
                    "caveat_html": html("#main_panel-caveat_html"),
                    "method_html": html("#main_panel-description_html"),
                    "metadata_html": html("#main_panel-update_source_html"),
                    "metadata_text": text("#main_panel-update_source_html"),
                    "source_url": source ? source.href : ""
                };
            }
            """
        )


class StatsGovtNzIndicatorsCrawler(BaseCrawler):
    site_id = "stats-govt-nz-indicators"
    site_name = "Custom: stats-govt-nz-indicators"
    base_url = "https://www.stats.govt.nz"

    START_URL = "https://www.stats.govt.nz/indicators/"
    SHINY_APP_URL = "https://statisticsnz.shinyapps.io/wellbeingindicators/"

    PAGE_SIZE = 10
    SAFETY_PAGE_CAP = 200
    WALL_CLOCK_SECONDS = 25 * 60
    DEADLINE_MARGIN_SECONDS = 30
    CURL_TIMEOUT = 45
    BROWSER_TIMEOUT_MS = 60000
    BACKOFF_SECONDS = (1, 3, 9)
    MIN_ABSTRACT_CHARS = 100

    def __init__(self, db_conn, delay=1.0, detail_delay=None):
        super().__init__(db_conn=db_conn, delay=delay)
        self.detail_delay = delay if detail_delay is None else detail_delay

    # ------------------------------------------------------------------
    # Main crawl
    # ------------------------------------------------------------------

    def crawl(self, limit=None):
        """Crawl the live Shiny list endpoint and indicator detail routes."""
        saved = 0
        page = 1
        seen_urls = set()
        started_at = time.monotonic()
        limit_or_inf = limit if limit is not None else "inf"
        client = None

        if limit is not None and limit <= 0:
            print(f"[{self.site_id}] done. Total saved: 0")
            return 0

        try:
            self._discover_starting_page()
            self._discover_shiny_app()

            client = self._start_shiny_client_with_retries()
            csv_text, list_endpoint = self._fetch_csv_with_retries(client)
            records = self._parse_indicator_csv(csv_text, list_endpoint)
            if not records:
                print(f"[{self.site_id}] no indicator records discovered")
                return 0

            print(
                f"[{self.site_id}] discovered {len(records)} indicators "
                f"from {list_endpoint}"
            )

            while page <= self.SAFETY_PAGE_CAP:
                if limit is not None and saved >= limit:
                    break
                if self._time_nearly_up(started_at):
                    print(f"[{self.site_id}] approaching 25 minute crawl budget; exiting cleanly")
                    break

                if page % 10 == 0:
                    print(f"[{self.site_id}] page {page}: saved {saved}/{limit_or_inf}")

                page_items = self._records_page(records, page)
                if not page_items:
                    print(f"[{self.site_id}] no more items at page {page}; done")
                    break

                new_items = []
                for record in page_items:
                    url = str(record.get("url") or "")
                    if not url or url in seen_urls:
                        continue
                    seen_urls.add(url)
                    new_items.append(record)

                if not new_items:
                    print(f"[{self.site_id}] page {page} returned 0 new records; stopping")
                    break

                for idx, record in enumerate(new_items, start=1):
                    if limit is not None and saved >= limit:
                        break
                    if self._time_nearly_up(started_at):
                        print(f"[{self.site_id}] approaching 25 minute crawl budget; exiting cleanly")
                        return saved

                    item_label = f"{page}.{idx}"
                    try:
                        time.sleep(self.detail_delay)
                        detail = self._fetch_detail_with_retries(client, record, item_label)
                        parsed = self._build_record(record, detail)
                        abstract = parsed.get("abstract") or ""
                        if len(abstract) < 50:
                            print(
                                f"[{self.site_id}] item {item_label} skipped: "
                                f"abstract shorter than 50 chars ({len(abstract)} chars)"
                            )
                            continue
                        if len(abstract) < self.MIN_ABSTRACT_CHARS:
                            print(
                                f"[{self.site_id}] item {item_label} skipped: "
                                f"abstract shorter than {self.MIN_ABSTRACT_CHARS} chars "
                                f"({len(abstract)} chars)"
                            )
                            continue

                        paper = {
                            "id": None,
                            "site_id": self.site_id,
                            "external_id": parsed["external_id"],
                            "title": parsed["title"],
                            "authors": json.dumps([], ensure_ascii=False),
                            "abstract": abstract,
                            "category": parsed["category"],
                            "keywords": json.dumps(parsed["keywords"], ensure_ascii=False),
                            "published_date": parsed["published_date"],
                            "url": parsed["url"],
                            "pdf_url": "",
                            "doi": "",
                            "department": parsed["department"],
                            "metadata": json.dumps(parsed["metadata"], ensure_ascii=False),
                        }
                        self._save_paper(paper)
                        saved += 1
                        counter = f"{saved}/{limit}" if limit is not None else str(saved)
                        print(f"[{self.site_id}] saved {counter}: {parsed['title'][:90]}")
                    except Exception as exc:
                        print(f"[{self.site_id}] item {item_label} failed: {exc}")
                        continue

                page += 1

            if page > self.SAFETY_PAGE_CAP:
                print(f"[{self.site_id}] reached safety page cap of {self.SAFETY_PAGE_CAP}; stopping")
        finally:
            if client is not None:
                client.close()

        print(f"[{self.site_id}] done. Total saved: {saved}")
        return saved

    # ------------------------------------------------------------------
    # Discovery / fetching
    # ------------------------------------------------------------------

    def _discover_starting_page(self):
        raw = self._curl_get(self.START_URL, context="starting URL")
        if not raw:
            return
        soup = self._make_soup(raw, context="starting URL")
        moved_links = []
        for link in soup.find_all("a", href=True):
            href = link.get("href") or ""
            if "wellbeingindicators" in href or "shinyapps.io/wellbeingindicators" in href:
                moved_links.append(href)
        if moved_links:
            print(f"[{self.site_id}] starting page points to {moved_links[0]}")
        elif "_Incapsula_Resource" in raw:
            print(f"[{self.site_id}] starting page returned Incapsula interstitial; using Shiny app")

    def _discover_shiny_app(self):
        raw = self._curl_get(self.SHINY_APP_URL, context="Shiny app bootstrap")
        if not raw:
            return
        soup = self._make_soup(raw, context="Shiny app bootstrap")
        base = soup.find("base")
        worker = base.get("href", "").strip("/") if base else ""
        if worker:
            print(f"[{self.site_id}] discovered Shiny worker bootstrap: {worker}")

    def _start_shiny_client_with_retries(self) -> _StatsNzShinyClient:
        last_error = ""
        for attempt, wait in enumerate(self.BACKOFF_SECONDS, start=1):
            client = _StatsNzShinyClient(self)
            try:
                return client.start()
            except Exception as exc:
                last_error = str(exc)
                client.close()
                if attempt < len(self.BACKOFF_SECONDS):
                    print(
                        f"[{self.site_id}] Shiny startup failed "
                        f"(attempt {attempt}/3): {last_error}; retrying in {wait}s"
                    )
                    time.sleep(wait)
        raise RuntimeError(f"Shiny startup failed after 3 attempts: {last_error}")

    def _fetch_csv_with_retries(self, client: _StatsNzShinyClient) -> tuple[str, str]:
        last_error = ""
        for attempt, wait in enumerate(self.BACKOFF_SECONDS, start=1):
            try:
                return client.fetch_all_data_csv()
            except Exception as exc:
                last_error = str(exc)
                if attempt < len(self.BACKOFF_SECONDS):
                    print(
                        f"[{self.site_id}] list endpoint failed "
                        f"(attempt {attempt}/3): {last_error}; retrying in {wait}s"
                    )
                    time.sleep(wait)
        raise RuntimeError(f"list endpoint failed after 3 attempts: {last_error}")

    def _fetch_detail_with_retries(
        self,
        client: _StatsNzShinyClient,
        record: Dict[str, object],
        item_label: str,
    ) -> Dict[str, str]:
        last_error = ""
        for attempt, wait in enumerate(self.BACKOFF_SECONDS, start=1):
            try:
                return client.fetch_indicator_detail(record)
            except Exception as exc:
                last_error = str(exc)
                if attempt < len(self.BACKOFF_SECONDS):
                    print(
                        f"[{self.site_id}] item {item_label} detail failed "
                        f"(attempt {attempt}/3): {last_error}; retrying in {wait}s"
                    )
                    time.sleep(wait)
        raise RuntimeError(f"detail fetch failed after 3 attempts: {last_error}")

    def _curl_get(self, url: str, context: str = "request", timeout: Optional[int] = None):
        timeout = timeout or self.CURL_TIMEOUT
        cmd = [
            "curl",
            "--tls-max",
            "1.3",
            "-skL",
            "--compressed",
            "--max-time",
            str(timeout),
            "-A",
            self.USER_AGENT,
            "-H",
            "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,application/json,*/*;q=0.8",
            "-H",
            "Accept-Language: en-NZ,en;q=0.9",
            url,
        ]
        last_error = ""
        for attempt, wait in enumerate(self.BACKOFF_SECONDS, start=1):
            try:
                result = subprocess.run(
                    cmd,
                    capture_output=True,
                    timeout=timeout + 5,
                    check=False,
                )
                if result.returncode == 0 and result.stdout:
                    return result.stdout.decode("utf-8", errors="replace")
                stderr = result.stderr.decode("utf-8", errors="replace").strip()
                last_error = stderr or f"curl exit {result.returncode}"
            except subprocess.TimeoutExpired as exc:
                last_error = f"timeout after {exc.timeout}s"
            except OSError as exc:
                last_error = str(exc)

            if attempt < len(self.BACKOFF_SECONDS):
                print(
                    f"[{self.site_id}] {context} curl failed "
                    f"(attempt {attempt}/3): {last_error}; retrying in {wait}s"
                )
                time.sleep(wait)

        print(f"[{self.site_id}] {context} curl failed after 3 attempts: {last_error}")
        return None

    # ------------------------------------------------------------------
    # Parsing / record construction
    # ------------------------------------------------------------------

    def _parse_indicator_csv(self, csv_text: str, list_endpoint: str) -> List[Dict[str, object]]:
        csv_text = (csv_text or "").lstrip("\ufeff")
        reader = csv.DictReader(io.StringIO(csv_text))
        grouped: "OrderedDict[tuple[str, str, str], Dict[str, object]]" = OrderedDict()

        for row in reader:
            klass = self._clean_text(row.get("class") or "")
            category = self._clean_text(row.get("category") or "")
            indicator = self._clean_text(row.get("indicator_name") or "")
            if not klass or not category or not indicator:
                continue

            key = (klass, category, indicator)
            if key not in grouped:
                grouped[key] = {
                    "class": klass,
                    "category_name": category,
                    "indicator_name": indicator,
                    "rows": 0,
                    "series_names": OrderedDict(),
                    "sub_series_names": OrderedDict(),
                    "units": OrderedDict(),
                    "dates": [],
                    "date_last_updated_values": [],
                    "list_endpoint": list_endpoint,
                }

            group = grouped[key]
            group["rows"] = int(group["rows"]) + 1
            for field, target in (
                ("series_name", "series_names"),
                ("sub_series_name", "sub_series_names"),
                ("units", "units"),
            ):
                value = self._clean_text(row.get(field) or "")
                if value:
                    group[target][value] = True
            date_value = self._clean_text(row.get("date") or "")
            if date_value:
                group["dates"].append(date_value)
            updated = self._clean_text(row.get("date_last_updated") or "")
            if updated:
                group["date_last_updated_values"].append(updated)

        records = []
        for group in grouped.values():
            group["series_names"] = list(group["series_names"].keys())
            group["sub_series_names"] = list(group["sub_series_names"].keys())
            group["units"] = list(group["units"].keys())
            group["published_date"] = self._latest_csv_update(
                group.get("date_last_updated_values") or []
            )
            group["url"] = self._detail_url(group)
            group["external_id"] = self._external_id(group)
            records.append(group)
        return records

    def _build_record(self, record: Dict[str, object], detail: Dict[str, str]) -> Dict[str, object]:
        title = str(record.get("indicator_name") or "").strip()
        klass = str(record.get("class") or "").strip()
        category_name = str(record.get("category_name") or "").strip()

        description = self._html_to_text(detail.get("description_html") or "", "description")
        description = self._remove_leading_title(description, title)
        summary = self._html_to_text(detail.get("summary_html") or "", "summary")
        caveat = self._html_to_text(detail.get("caveat_html") or "", "caveat")
        method = self._html_to_text(detail.get("method_html") or "", "methodology")
        meta_text = self._html_to_text(detail.get("metadata_html") or "", "metadata")
        meta = self._parse_metadata_text(meta_text)

        fallback = self._csv_fallback_abstract(record)
        abstract = self._join_limited(
            [description, summary, caveat, method, fallback],
            limit=4000,
        )

        detail_date = self._parse_date(meta.get("last_updated") or "")
        published_date = detail_date or str(record.get("published_date") or "")
        source = meta.get("source") or "Stats NZ Tatauranga Aotearoa"

        series_names = record.get("series_names") or []
        sub_series_names = record.get("sub_series_names") or []
        units = record.get("units") or []
        keywords = self._dedupe(
            [klass, category_name]
            + list(series_names)[:20]
            + list(sub_series_names)[:20]
            + list(units)[:10]
        )

        metadata = {
            "start_url": self.START_URL,
            "shiny_app_url": self.SHINY_APP_URL,
            "list_endpoint": record.get("list_endpoint"),
            "detail_endpoint": record.get("url"),
            "class": klass,
            "category": category_name,
            "indicator_name": title,
            "row_count": record.get("rows"),
            "series_names": series_names,
            "sub_series_names_sample": list(sub_series_names)[:50],
            "units": units,
            "date_range": self._date_range(record.get("dates") or []),
            "csv_last_updated_values": self._dedupe(record.get("date_last_updated_values") or []),
            "detail_last_updated": meta.get("last_updated"),
            "frequency": meta.get("frequency"),
            "source": source,
            "source_url": detail.get("source_url") or "",
        }

        return {
            "external_id": record.get("external_id"),
            "title": title,
            "abstract": abstract,
            "category": f"{klass} / {category_name}".strip(" /"),
            "keywords": keywords,
            "published_date": published_date,
            "url": record.get("url"),
            "department": source,
            "metadata": metadata,
        }

    def _html_to_text(self, html: str, context: str) -> str:
        soup = self._make_soup(html or "", context=context)
        text = soup.get_text("\n", strip=True)
        return self._clean_text(text)

    def _make_soup(self, raw: str, context: str = "HTML") -> BeautifulSoup:
        last_error = None
        for parser in ("html5lib", "lxml", "html.parser"):
            try:
                return BeautifulSoup(raw or "", parser)
            except Exception as exc:
                last_error = exc
                print(f"[{self.site_id}] BeautifulSoup({parser}) failed for {context}: {exc}")
        print(f"[{self.site_id}] all BeautifulSoup parsers failed for {context}: {last_error}")
        return BeautifulSoup("", "html.parser")

    @staticmethod
    def _clean_text(value: str) -> str:
        value = (value or "").replace("\xa0", " ")
        return re.sub(r"\s+", " ", value).strip()

    @staticmethod
    def _dedupe(values) -> List[str]:
        seen = set()
        result = []
        for value in values:
            value = str(value or "").strip()
            if not value or value in seen:
                continue
            seen.add(value)
            result.append(value)
        return result

    def _csv_fallback_abstract(self, record: Dict[str, object]) -> str:
        title = str(record.get("indicator_name") or "")
        klass = str(record.get("class") or "")
        category = str(record.get("category_name") or "")
        series = ", ".join(list(record.get("series_names") or [])[:8])
        units = ", ".join(list(record.get("units") or [])[:6])
        date_range = self._date_range(record.get("dates") or [])
        updated = str(record.get("published_date") or "")
        return self._clean_text(
            f"{title} is an Indicators Aotearoa New Zealand indicator in the "
            f"{klass} class and {category} topic. The public Stats NZ all-data "
            f"download includes {record.get('rows')} observations"
            f"{' across series including ' + series if series else ''}"
            f"{' with units including ' + units if units else ''}. "
            f"The available data span is {date_range or 'not specified'}, and "
            f"the latest update recorded in the downloaded dataset is {updated or 'not specified'}."
        )

    def _remove_leading_title(self, text: str, title: str) -> str:
        if text.startswith(title):
            text = text[len(title):]
        return text.strip(" -:\n\t ")

    def _parse_metadata_text(self, text: str) -> Dict[str, str]:
        parts = [p.strip() for p in re.split(r"\n+|\s{2,}", text or "") if p.strip()]
        if len(parts) <= 1:
            parts = re.findall(
                r"(Last updated|Frequency|Source)\s+(.+?)(?=\s+(?:Last updated|Frequency|Source)\s+|$)",
                text or "",
            )
            return {
                label.lower().replace(" ", "_"): self._clean_text(value)
                for label, value in parts
            }

        result = {}
        for idx, value in enumerate(parts):
            label = value.lower().replace(" ", "_")
            if label in {"last_updated", "frequency", "source"} and idx + 1 < len(parts):
                result[label] = self._clean_text(parts[idx + 1])
        return result

    def _latest_csv_update(self, values) -> str:
        parsed_dates = []
        for value in values:
            parsed = self._parse_date(value)
            if parsed:
                parsed_dates.append(parsed)
        return max(parsed_dates) if parsed_dates else ""

    @staticmethod
    def _parse_date(value: str) -> str:
        value = (value or "").strip()
        if not value:
            return ""
        for fmt in ("%d-%m-%y", "%d-%m-%Y", "%d %B %Y", "%Y-%m-%d"):
            try:
                return datetime.strptime(value, fmt).date().isoformat()
            except ValueError:
                pass
        match = re.search(r"\d{4}-\d{2}-\d{2}", value)
        return match.group(0) if match else ""

    def _date_range(self, values) -> str:
        clean = self._dedupe(values)
        if not clean:
            return ""
        try:
            return f"{min(clean)} to {max(clean)}"
        except Exception:
            return ""

    def _join_limited(self, parts, limit: int = 4000) -> str:
        text = "\n\n".join(self._dedupe([self._clean_text(p) for p in parts]))
        if len(text) <= limit:
            return text
        cut = text[:limit].rsplit(" ", 1)[0].rstrip(" .,;:")
        return cut

    def _route_path(self, record: Dict[str, object]) -> str:
        return "/?" + urlencode(
            {
                "page": "indicators",
                "class": str(record.get("class") or ""),
                "type": str(record.get("category_name") or ""),
                "indicator": str(record.get("indicator_name") or ""),
            }
        )

    def _detail_url(self, record: Dict[str, object]) -> str:
        return self.SHINY_APP_URL.rstrip("/") + self._route_path(record)

    def _external_id(self, record: Dict[str, object]) -> str:
        basis = "|".join(
            [
                str(record.get("class") or ""),
                str(record.get("category_name") or ""),
                str(record.get("indicator_name") or ""),
            ]
        )
        digest = hashlib.sha1(basis.encode("utf-8")).hexdigest()[:16]
        slug = re.sub(r"[^a-z0-9]+", "-", basis.lower()).strip("-")[:80]
        return f"{slug}-{digest}"

    def _records_page(self, records: List[Dict[str, object]], page: int):
        start = (page - 1) * self.PAGE_SIZE
        end = start + self.PAGE_SIZE
        return records[start:end]

    def _time_nearly_up(self, started_at: float) -> bool:
        return time.monotonic() - started_at >= (
            self.WALL_CLOCK_SECONDS - self.DEADLINE_MARGIN_SECONDS
        )


__all__ = ["StatsGovtNzIndicatorsCrawler"]
